"""Hand-crafted fresh-goods reference dataset for 20 canonical AU grocery SKUs."""

from typing import Literal

import numpy as np
from pydantic import BaseModel


class FreshGoodSpec(BaseModel):
    name: str
    category: str
    subcategory: str
    unit_of_measure: Literal["each", "kg", "g", "L", "mL", "pack"]
    pack_size: float
    cost_price_aud: float
    shelf_life_days: int
    wastage_rate_baseline: float
    peak_months: list[int]
    seasonality_vector: list[float]


def _wobble(name: str) -> list[float]:
    rng = np.random.default_rng(hash(name) % 2**32)
    return [round(float(v), 2) for v in rng.uniform(0.90, 1.10, 12)]


FRESH_GOODS_REFERENCE: list[FreshGoodSpec] = [
    FreshGoodSpec(
        name="Mango Kensington Pride",
        category="Fruit",
        subcategory="Tropical Fruit",
        unit_of_measure="each",
        pack_size=1.0,
        cost_price_aud=1.80,
        shelf_life_days=7,
        wastage_rate_baseline=0.08,
        peak_months=[11, 12, 1, 2, 3],
        seasonality_vector=[1.6, 1.8, 1.4, 0.6, 0.3, 0.2, 0.2, 0.2, 0.4, 0.8, 1.4, 1.8],
    ),
    FreshGoodSpec(
        name="Banana Cavendish",
        category="Fruit",
        subcategory="Tropical Fruit",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=1.95,
        shelf_life_days=6,
        wastage_rate_baseline=0.05,
        peak_months=[],
        seasonality_vector=_wobble("Banana Cavendish"),
    ),
    FreshGoodSpec(
        name="Strawberry 250g punnet",
        category="Fruit",
        subcategory="Berries",
        unit_of_measure="pack",
        pack_size=250.0,
        cost_price_aud=2.40,
        shelf_life_days=4,
        wastage_rate_baseline=0.12,
        peak_months=[8, 9, 10, 11, 12],
        seasonality_vector=[0.6, 0.5, 0.4, 0.4, 0.5, 0.6, 0.7, 1.0, 1.5, 1.8, 1.6, 1.2],
    ),
    FreshGoodSpec(
        name="Avocado Hass",
        category="Fruit",
        subcategory="Tropical Fruit",
        unit_of_measure="each",
        pack_size=1.0,
        cost_price_aud=1.20,
        shelf_life_days=10,
        wastage_rate_baseline=0.07,
        peak_months=[5, 6, 7, 8, 9, 10, 11, 12, 1],
        seasonality_vector=[1.2, 1.1, 0.9, 0.7, 0.9, 1.1, 1.2, 1.2, 1.1, 1.0, 1.1, 1.2],
    ),
    FreshGoodSpec(
        name="Apple Pink Lady",
        category="Fruit",
        subcategory="Pome Fruit",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=3.10,
        shelf_life_days=30,
        wastage_rate_baseline=0.03,
        peak_months=[4, 5, 6, 7, 8, 9],
        seasonality_vector=[0.7, 0.7, 0.8, 1.2, 1.4, 1.4, 1.3, 1.2, 1.1, 0.9, 0.7, 0.6],
    ),
    FreshGoodSpec(
        name="Apple Granny Smith",
        category="Fruit",
        subcategory="Pome Fruit",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=2.80,
        shelf_life_days=30,
        wastage_rate_baseline=0.03,
        peak_months=[],
        seasonality_vector=_wobble("Apple Granny Smith"),
    ),
    FreshGoodSpec(
        name="Peach Yellow",
        category="Fruit",
        subcategory="Stone Fruit",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=4.50,
        shelf_life_days=5,
        wastage_rate_baseline=0.10,
        peak_months=[12, 1, 2, 3],
        seasonality_vector=[1.4, 1.2, 1.0, 0.4, 0.2, 0.1, 0.1, 0.1, 0.2, 0.5, 0.9, 1.3],
    ),
    FreshGoodSpec(
        name="Cherry 500g",
        category="Fruit",
        subcategory="Stone Fruit",
        unit_of_measure="pack",
        pack_size=500.0,
        cost_price_aud=8.00,
        shelf_life_days=4,
        wastage_rate_baseline=0.15,
        peak_months=[11, 12, 1],
        seasonality_vector=[2.4, 1.0, 0.2, 0.1, 0.05, 0.05, 0.05, 0.05, 0.1, 0.4, 1.6, 3.0],
    ),
    FreshGoodSpec(
        name="Watermelon Seedless",
        category="Fruit",
        subcategory="Tropical Fruit",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=1.40,
        shelf_life_days=14,
        wastage_rate_baseline=0.06,
        peak_months=[11, 12, 1, 2, 3],
        seasonality_vector=[1.5, 1.5, 1.2, 0.6, 0.3, 0.2, 0.2, 0.3, 0.5, 0.9, 1.3, 1.6],
    ),
    FreshGoodSpec(
        name="Tomato Truss",
        category="Vegetables",
        subcategory="Salad Vegetables",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=3.20,
        shelf_life_days=10,
        wastage_rate_baseline=0.06,
        peak_months=[],
        seasonality_vector=_wobble("Tomato Truss"),
    ),
    FreshGoodSpec(
        name="Lettuce Iceberg",
        category="Vegetables",
        subcategory="Leafy Greens",
        unit_of_measure="each",
        pack_size=1.0,
        cost_price_aud=1.80,
        shelf_life_days=7,
        wastage_rate_baseline=0.10,
        peak_months=[],
        seasonality_vector=_wobble("Lettuce Iceberg"),
    ),
    FreshGoodSpec(
        name="Cucumber Lebanese",
        category="Vegetables",
        subcategory="Salad Vegetables",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=3.50,
        shelf_life_days=10,
        wastage_rate_baseline=0.07,
        peak_months=[],
        seasonality_vector=_wobble("Cucumber Lebanese"),
    ),
    FreshGoodSpec(
        name="Capsicum Red",
        category="Vegetables",
        subcategory="Salad Vegetables",
        unit_of_measure="each",
        pack_size=1.0,
        cost_price_aud=1.50,
        shelf_life_days=10,
        wastage_rate_baseline=0.08,
        peak_months=[],
        seasonality_vector=_wobble("Capsicum Red"),
    ),
    FreshGoodSpec(
        name="Carrot Loose",
        category="Vegetables",
        subcategory="Root Vegetables",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=1.50,
        shelf_life_days=30,
        wastage_rate_baseline=0.04,
        peak_months=[],
        seasonality_vector=_wobble("Carrot Loose"),
    ),
    FreshGoodSpec(
        name="Potato Brushed",
        category="Vegetables",
        subcategory="Root Vegetables",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=2.20,
        shelf_life_days=60,
        wastage_rate_baseline=0.03,
        peak_months=[],
        seasonality_vector=_wobble("Potato Brushed"),
    ),
    FreshGoodSpec(
        name="Onion Brown",
        category="Vegetables",
        subcategory="Root Vegetables",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=1.80,
        shelf_life_days=60,
        wastage_rate_baseline=0.03,
        peak_months=[],
        seasonality_vector=_wobble("Onion Brown"),
    ),
    FreshGoodSpec(
        name="Broccoli",
        category="Vegetables",
        subcategory="Cruciferous",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=4.00,
        shelf_life_days=7,
        wastage_rate_baseline=0.10,
        peak_months=[5, 6, 7, 8, 9, 10],
        seasonality_vector=[0.5, 0.6, 0.8, 1.0, 1.4, 1.5, 1.5, 1.4, 1.2, 1.0, 0.7, 0.5],
    ),
    FreshGoodSpec(
        name="Cauliflower",
        category="Vegetables",
        subcategory="Cruciferous",
        unit_of_measure="each",
        pack_size=1.0,
        cost_price_aud=3.50,
        shelf_life_days=10,
        wastage_rate_baseline=0.08,
        peak_months=[5, 6, 7, 8, 9, 10],
        seasonality_vector=[0.5, 0.6, 0.8, 1.0, 1.4, 1.5, 1.5, 1.4, 1.2, 1.0, 0.7, 0.5],
    ),
    FreshGoodSpec(
        name="Pumpkin Butternut",
        category="Vegetables",
        subcategory="Squash & Pumpkin",
        unit_of_measure="kg",
        pack_size=1.0,
        cost_price_aud=2.20,
        shelf_life_days=60,
        wastage_rate_baseline=0.04,
        peak_months=[3, 4, 5, 6, 7, 8],
        seasonality_vector=[0.6, 0.7, 1.2, 1.5, 1.5, 1.4, 1.3, 1.1, 0.9, 0.7, 0.6, 0.6],
    ),
    FreshGoodSpec(
        name="Asparagus Bunch",
        category="Vegetables",
        subcategory="Salad Vegetables",
        unit_of_measure="pack",
        pack_size=250.0,
        cost_price_aud=4.50,
        shelf_life_days=4,
        wastage_rate_baseline=0.18,
        peak_months=[9, 10, 11, 12],
        seasonality_vector=[0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.7, 1.5, 2.0, 1.8, 1.0],
    ),
]

for _spec in FRESH_GOODS_REFERENCE:
    assert len(_spec.seasonality_vector) == 12, f"{_spec.name}: vector length != 12"
    assert all(v >= 0 for v in _spec.seasonality_vector), f"{_spec.name}: negative value in vector"
